
export const Section9Content = [
    {
        title: 'RealEstate',
         content: [
            {name: 'New York'},
            {name: 'Brooklyn'},
            {name: 'Calhoun'},
            {name: 'Charlote'},
            {name: 'Citrus'},
            {name: 'Clay'},
            {name: 'Coller'},
            {name: 'Queens'},
            {name: 'The Bronx'},
            {name: 'Staten'},
            {name: 'Jersey'},
            {name: 'Lake'},
            {name: 'Will'},
            {name: 'DuPage'},
            {name: 'Miami'},
            {name: 'Norwalk'},
            {name: 'Downey'},
            {name: 'Torrance'},
            {name: 'Pomona'},
            {name: 'Glendale'},
            {name: 'Inglewood'},
            {name: 'Chicago'},
            {name: 'Cook'},
            {name: 'Kane'},
        ]
    },
    {
        title: 'New Homes',
        content: [
            {name: 'New York'},
            {name: 'Brooklyn'},
            {name: 'Queens'},
            {name: 'Torrance'},
            {name: 'Lake'},
            {name: 'Will'},
            {name: 'DuPage'},
            {name: 'Miami'},
            {name: 'Calhoun'},
            {name: 'Charlote'},
            {name: 'Citrus'},
            {name: 'Pomona'},
            {name: 'Glendale'},
            {name: 'Inglewood'},
            {name: 'Chicago'},
            {name: 'Cook'},
            {name: 'The Bronx'},
            {name: 'Staten'},
            {name: 'Jersey'},
            {name: 'Norwalk'},
            {name: 'Downey'},
            {name: 'Kane'},
            {name: 'Clay'},
            {name: 'Coller'},
        ]
    },
    {
        title: 'Popular Areas',
        content: [
            {name: 'New York'},
            {name: 'Brooklyn'},
            {name: 'Queens'},
            {name: 'The Bronx'},
            {name: 'Staten'},
            {name: 'Pomona'},
            {name: 'Glendale'},
            {name: 'Lake'},
            {name: 'Will'},
            {name: 'DuPage'},
            {name: 'Miami'},
            {name: 'Calhoun'},
            {name: 'Charlote'},
            {name: 'Citrus'},
            {name: 'Clay'},
            {name: 'Coller'},
            {name: 'Inglewood'},
            {name: 'Chicago'},
            {name: 'Jersey'},
            {name: 'Norwalk'},
            {name: 'Downey'},
            {name: 'Torrance'},
            {name: 'Cook'},
            {name: 'Kane'},
           
        ]
    },
    {
        title: 'Popular searches',
        content: [
            {name: 'New York'},
            {name: 'Brooklyn'},
            {name: 'Queens'},
            {name: 'The Bronx'},
            {name: 'Staten'},
            {name: 'Jersey'},
            {name: 'Norwalk'},
            {name: 'Downey'},
            {name: 'Torrance'},
            {name: 'Pomona'},
            {name: 'Glendale'},
            {name: 'Inglewood'},
            {name: 'Chicago'},
            {name: 'Cook'},
            {name: 'Kane'},
            {name: 'Lake'},
            {name: 'Will'},
            {name: 'DuPage'},
            {name: 'Miami'},
            {name: 'Calhoun'},
            {name: 'Charlote'},
            {name: 'Citrus'},
            {name: 'Clay'},
            {name: 'Coller'},
        ]
    }
]